import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    // Vendored shadcn/ui primitives. These are generated by `shadcn add` and
    // overwritten whenever a component is re-added, so hand-editing them to
    // satisfy lint would be undone by the next update — and the patterns being
    // flagged are upstream's own design, not defects introduced here:
    //
    //   only-export-components — shadcn deliberately ships the cva variants
    //     next to the component (`buttonVariants`, `badgeVariants`, …) because
    //     consumers compose with them. Splitting the files would break every
    //     import site for a dev-only fast-refresh optimisation.
    //   purity — <SidebarMenuSkeleton> randomises its placeholder width so a
    //     column of skeletons looks uneven. Decorative, and it is already
    //     memoised per instance.
    //   set-state-in-effect — <Carousel> mirrors the Embla api instance up to
    //     the optional `setApi` prop; the instance only exists after Embla
    //     initialises, so an effect is the only place it can be published.
    //
    // Deliberately narrow: anything else in these files still gets linted.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
])
